## Code Editors
set -gx EDITOR nano
set -gx VISUAL nano

## Home Cleanup: XDG Base Directory
## Source 0: https://wiki.archlinux.org/title/XDG_Base_Directory#Partial
## Source 1: https://github.com/b3nj5m1n/xdg-ninja
set -gx _JAVA_OPTIONS "-Djava.util.prefs.userRoot=$XDG_CONFIG_HOME/java"
set -gx ANDROID_HOME "$XDG_DATA_HOME/android/sdk"
set -gx ANDROID_USER_HOME "$XDG_DATA_HOME/android"
set -gx AWS_CONFIG_FILE "$XDG_CONFIG_HOME/aws/config"
set -gx AWS_SHARED_CREDENTIALS_FILE "$XDG_CONFIG_HOME/aws/credentials"
set -gx BUNDLE_USER_CACHE "$XDG_CACHE_HOME/bundle"
set -gx BUNDLE_USER_CONFIG "$XDG_CONFIG_HOME/bundle"
set -gx BUNDLE_USER_PLUGIN "$XDG_DATA_HOME/bundle"
set -gx CARGO_HOME "$XDG_DATA_HOME/cargo"
set -gx CUDA_CACHE_PATH "$XDG_DATA_HOME/nv"
set -gx DOCKER_CONFIG "$XDG_CONFIG_HOME/docker"
set -gx DOTNET_CLI_HOME "$XDG_DATA_HOME/dotnet"
set -gx FMPEG_DATADIR "$XDG_CONFIG_HOME/ffmpeg"
set -gx GNUPGHOME "$XDG_DATA_HOME/gnupg"
set -gx GOMODCACHE "$XDG_CACHE_HOME/go/mod"
set -gx GOPATH "$XDG_DATA_HOME/go"
set -gx GRADLE_USER_HOME "$XDG_DATA_HOME/gradle"
set -gx GTK_RC_FILES "$XDG_CONFIG_HOME"/gtk-1.0/gtkrc
set -gx GTK2_RC_FILES "$XDG_CONFIG_HOME/gtk-2.0/gtkrc":"$XDG_CONFIG_HOME/gtk-2.0/gtkrc.mine"
set -gx NODE_REPL_HISTORY "$XDG_DATA_HOME/node_repl_history"
set -gx NPM_CONFIG_USERCONFIG "$XDG_CONFIG_HOME/npm/npmrc"
set -gx NUGET_PACKAGES "$XDG_CACHE_HOME/NuGetPackages"
set -gx PGPASSFILE "$XDG_CONFIG_HOME/pg/pgpass"
set -gx PGSERVICEFILE "$XDG_CONFIG_HOME/pg/pg_service.conf"
set -gx PSQL_HISTORY "$XDG_STATE_HOME/psql_history"
set -gx PSQLRC "$XDG_CONFIG_HOME/pg/psqlrc"
set -gx RUSTUP_HOME "$XDG_DATA_HOME/rustup"
set -gx SCREENDIR "$XDG_RUNTIME_DIR/screen"
set -gx SCREENRC "$XDG_CONFIG_HOME/screen/screenrc"
set -gx SQLITE_HISTORY $XDG_STATE_HOME/sqlite_history
set -gx TS3_CONFIG_DIR "$XDG_CONFIG_HOME/ts3client"
set -gx VOLTA_HOME "$XDG_DATA_HOME/volta"
